# Generated by Django 5.x

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryMachine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("machine_id", models.CharField(db_index=True, max_length=128, unique=True)),
                ("volunteer_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("hostname", models.CharField(blank=True, max_length=255)),
                ("os_name", models.CharField(blank=True, max_length=64)),
                ("cpu_model", models.CharField(blank=True, max_length=255)),
                ("cpu_cores", models.IntegerField(default=0)),
                ("ram_gb", models.FloatField(default=0)),
                ("disk_total_gb", models.FloatField(default=0)),
                ("timezone", models.CharField(blank=True, max_length=64)),
                ("consent_level", models.IntegerField(default=3)),
                ("allowed_days", models.JSONField(blank=True, default=list)),
                ("allowed_slots", models.JSONField(blank=True, default=list)),
                ("contrib_mode", models.CharField(blank=True, max_length=32)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("snapshot_count", models.IntegerField(default=0)),
            ],
            options={"ordering": ["-last_seen"]},
        ),
        migrations.CreateModel(
            name="TelemetrySession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(max_length=64, unique=True)),
                ("boot_time", models.CharField(blank=True, max_length=64)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="portal.telemetrymachine",
                    ),
                ),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="TelemetrySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("predicted_availability", models.FloatField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="portal.telemetrymachine",
                    ),
                ),
            ],
            options={"ordering": ["-collected_at"]},
        ),
        migrations.CreateModel(
            name="TelemetryPowerEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=64)),
                ("gap_s", models.IntegerField(default=0)),
                ("ts_utc", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_events",
                        to="portal.telemetrymachine",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddIndex(
            model_name="telemetrysnapshot",
            index=models.Index(fields=["machine", "-collected_at"], name="portal_tele_machine_idx"),
        ),
    ]
